all: prog1 prog2 prog4 prog5 prog6 prog7

prog1: esercizio1.cc
	g++ -o prog1 esercizio1.cc

prog2: esercizio2.cc
	g++ -o prog2 esercizio2.cc

prog4: esercizio4.cc
	g++ -o prog4 esercizio4.cc

prog5: esercizio5.cc
	g++ -o prog5 esercizio5.cc

prog6: esercizio6.cc
	g++ -o prog6 esercizio6.cc

prog7: esercizio7.cc
	g++ -o prog7 esercizio7.cc

clean:
	rm prog1 prog2 prog4 prog5 prog6 prog7
