CC = g++

all: prog1 prog2 prog3 prog4 prog5

prog1: esercizio1.cc
	$(CC) -o $@ $<

prog2: esercizio2.cc
	$(CC) -o $@ $<

prog3: esercizio3.cc
	$(CC) -o $@ $<

prog4: esercizio4.cc
	$(CC) -o $@ $<

prog5: esercizio5.cc
	$(CC) -o $@ $<

clean:
	rm prog1 prog2 prog3 prog4 prog5 risultato.dat
